---
NONMEM_directory: /Users/jeff/nm751
NONMEM_version: 7.5
PsN_version: 5.5.0
command_line: /usr/local/bin/execute test_model.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  crash_restarts: 5
  debug_rmd: 0
  degree: 0.1
  directory: /Users/jeff/Desktop/nonmem_project/test_nonmem/modelfit_dir3/
  display_iterations: 1
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: default
  nmfe: 1
  nodes: 0
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 862961
  send_email: 0
  shrinkage: 0
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /Library/Perl/5.34/PsN_5_5_0/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: 5
  tweak_inits: 1
  verbose: 0
  zip: 1
copied_files:
  - test_model.lst
  - test_model.ext
  - test_model.cov
  - test_model.cor
  - test_model.coi
  - test_model.phi
  - sdtab107
finish_time: 2025-01-30 11:33:00
model_files:
  - /Users/jeff/Desktop/nonmem_project/test_nonmem/test_model.mod
start_time: 2025-01-30 11:32:51
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
